{% set name = "conda-bonjour" %}
{% set version = "0.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/BolunDai0216/conda-bonjour/archive/v{{ version }}.tar.gz
  sha256: 423756207559b0751f5541a321119c0f388ed74275e74628f7540db1a8c57e11

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=61.0.0
    - pybind11 >=2.10.0
    - cmake
    - wheel
    - pip
  run:
    - python >=3.8
    - numpy >=1.26.4

test:
  imports:
    - conda_bonjour
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/BolunDai0216/conda-bonjour
  summary: Tutorial on publishing to Conda
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - BolunDai0216
